# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-23 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='tagline',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='store',
            name='website',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
