# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-23 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_auto_20160123_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeaddress',
            name='zip_code',
            field=models.CharField(default=90210, max_length=20),
            preserve_default=False,
        ),
    ]
