# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-23 20:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_storeaddress_zip_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storeaddress',
            old_name='point',
            new_name='coords',
        ),
        migrations.AlterField(
            model_name='store',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='stores.StoreCategory'),
        ),
        migrations.AlterField(
            model_name='store',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='stores.StoreOwner'),
        ),
        migrations.AlterField(
            model_name='storeaddress',
            name='store',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='stores.Store'),
        ),
    ]
