# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 00:03
from __future__ import unicode_literals

import blockhunt.stores.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_auto_20160123_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='bounty',
            field=models.DecimalField(decimal_places=8, default='0.00000001', max_digits=10, validators=[blockhunt.stores.models.validate_bounty]),
            preserve_default=False,
        ),
    ]
