# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_store_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='balance',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=14),
        ),
    ]
