# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0007_auto_20160124_0431'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='coinbase_account_id',
            field=models.CharField(default='', editable=False, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='store',
            name='balance',
            field=models.DecimalField(decimal_places=8, default=0, editable=False, max_digits=14),
        ),
    ]
