# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 04:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_store_balance'),
        ('hunts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('reward', models.DecimalField(decimal_places=8, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='hunter',
            name='balance',
            field=models.DecimalField(decimal_places=8, default=0, help_text='The number of bitoins the hunter owns.', max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkin',
            name='hunter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='hunts.Hunter'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='stores.Store'),
        ),
    ]
