# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0002_auto_20160124_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hunter',
            name='balance',
            field=models.DecimalField(decimal_places=8, default=0, help_text='The number of bitoins the hunter owns.', max_digits=12),
        ),
    ]
