# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0004_auto_20160124_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hunter',
            name='balance',
            field=models.DecimalField(decimal_places=8, default=0, help_text='The number of bitoins the hunter owns.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='hunter',
            name='coinbase_account_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
